### ISSUE TITLE
After login via facebook all api calls fail with 401 - even logout

### ISSUE THREAD

**Issue by ctaylo21** [adeperio/base#68]
I have logged in successfully via Facebook on localhost but now all button clicks return a 401. Am I hitting something not implemented or is something not set up right? I am using newer versions of node and other things so it could be a version issue. I do have some deprecated warnings.

**Comment by ctaylo21** [comment]
I've found the error as a 'Error: Origin is not allowed by Access-Control-Allow-Origin' error. This seems like it's probably a common issue when using https + all the security measures locally. Is there a common workaround for development?

**Comment by ctaylo21** [comment]
Adding ```  res.header("Access-Control-Allow-Origin", "*");``` to the logout route fixed the issue but obviously this can't be used in production. I'm fine with removing it later but my open question still stands as far as local development goes: Is there a standard way to develop locally with this setup? Does it matter that you have all the https warnings and have to do some small security hacks to get things working ?

**Comment by adeperio** [comment]
Hi @ctaylo21, just getting back on a round of development with Base this month, Xmas was a pretty busy period :) In terms of running it locally, I haven't seen that error before. The one thing you should probably do is make sure your hosts file is set correctly (127.0.0.1 <yourdomain>.com). Could you try that and see if you can get things going without this error?

**Comment by adeperio** [comment]
On another note @ctaylo21, running locally requires a few things to be in place that differs from a production instance. We always run over https, but we use self-signed certs to run locally. Also, as mentioned above, your hosts file needs to be correctly set to have your site DNS point to 127.0.0.1 when running on your local machine (remember to navigate to your site using the port as well e.g https://<yourdomain.com:3000>). Also, when starting base for the first time, you will likely be greeted with a warning from your browser indicating you should check your SSL connection. This is because we are using self signed certs on a local instance. You should be presented with an option to continue to the site anyway. Selecting this and continuing through should get you running Base up locally.
